---
title: "In-Class Exercise 2"
author: "Emily Aurelia"
format:
  html:
    code-fold: true
    #code-summary: "Show the code"
    toc-depth: 4
execute: 
  eval: true
  echo: true
  warning: false #to remove the warning in the webpage
editor: visual
date: "`r Sys.Date()`"
---

## Getting Started

```{r}
#| code-summary: "Load the libraries needed for this In-Class Exercise"
pacman::p_load(arrow, lubridate, tidyverse, tmap, sf)
```

## Importing Grab-Posisi Dataset

```{r}
#| code-summary: Import Dataset
#| eval: false
df <- read_parquet("data/GrabPosisi/part-00000-8bbff892-97d2-4011-9961-703e38972569.c000.snappy.parquet")
df
```

```{r}
#| code-summary: Convert data type of pingtimestamp from integer to date-time
#| eval: false

df$pingtimestamp <- as_datetime(df$pingtimestamp)
```

```{r}
#| code-summary: Save the reformatted df into a new rds file called part0.rds
#| eval: false

write_rds(df, "data/rds/part0.rds")
```

## Extracting trip starting locations

```{r}
#| eval: false

origin_df <- df %>% 
  group_by(trj_id) %>% 
  arrange(pingtimestamp) %>% #arrange the time in ascending order
  filter(row_number()==1) %>% #choose the first location 
  mutate(weekday = wday(pingtimestamp, 
                        label=TRUE,
                        abbr=TRUE),
         start_hr = factor(hour(pingtimestamp)),
         day = factor(mday(pingtimestamp)))

origin_df
```

## Extracting trip ending locations

```{r}
#| eval: false

destination_df <- df %>% 
  group_by(trj_id) %>% 
  arrange(desc(pingtimestamp)) %>% #arrange the time in descending order
  filter(row_number()==1) %>% #choose the first location 
  mutate(weekday = wday(pingtimestamp, 
                        label=TRUE,
                        abbr=TRUE),
         end_hr = factor(hour(pingtimestamp)),
         day = factor(mday(pingtimestamp)))

destination_df
```

```{r}
#| code-summary: to save the dataframe as a rds file
#| eval: false

#can use echo: false so that this code is not shown
write_rds(origin_df, "data/rds/origin_df.rds")

write_rds(destination_df, "data/rds/destination_df.rds")
```


```{r}
#| code-summary: to read the rds file

origin_df <- read_rds("data/rds/origin_df.rds")
destination_df <- read_rds("data/rds/destination_df.rds")
```

